# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/snooper_pkg',
                'doc_host': 'https://sayanbanerjee32.github.io',
                'git_url': 'https://github.com/sayanbanerjee32/snooper_pkg',
                'lib_path': 'snooper_pkg'},
  'syms': {'snooper_pkg.core': {'snooper_pkg.core.foo': ('core.html#foo', 'snooper_pkg/core.py')}}}
