# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/snooper_pkg',
                'doc_host': 'https://sayanbanerjee32.github.io',
                'git_url': 'https://github.com/sayanbanerjee32/snooper_pkg',
                'lib_path': 'snooper_pkg'},
  'syms': { 'snooper_pkg.config': {},
            'snooper_pkg.db': { 'snooper_pkg.db.Event': ('db.html#event', 'snooper_pkg/db.py'),
                                'snooper_pkg.db.get_processes': ('db.html#get_processes', 'snooper_pkg/db.py'),
                                'snooper_pkg.db.log_event': ('db.html#log_event', 'snooper_pkg/db.py')}}}
