"""Central configuration values for Snooper's monitoring, data retention, reporting, privacy, and pause behaviour.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/config.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto #0
__all__ = ['APP_NAME', 'LOG_FILENAME', 'LOG_LEVEL', 'PROCESS_MONITORING_INTERVAL_SECONDS', 'EXCLUDED_PROCESSES',
           'DATABASE_FILENAME', 'DATA_RETENTION_DAYS', 'FG_APP_MONITORING_INTERVAL_SECONDS',
           'FG_APP_MONITORING_MIN_IDLE_SECONDS', 'STREAMING_APP_MIN_IDLE_SECONDS', 'NUM_TOP_APP_IN_REPORT',
           'NUM_TOP_WINDOW_IN_REPORT', 'SHOW_WINDOW_TITLES', 'DEFAULT_PAUSE_MINUTES']

# %% ../nbs/00_config.ipynb #f2a11914
APP_NAME = "Snooper"


# %% ../nbs/00_config.ipynb #2c47f2da
LOG_FILENAME = "snooper.log"

# %% ../nbs/00_config.ipynb #e0c32039
LOG_LEVEL = "WARNING"  # DEBUG, INFO, WARNING, ERROR

# %% ../nbs/00_config.ipynb #f99ee53a
PROCESS_MONITORING_INTERVAL_SECONDS = 5

# %% ../nbs/00_config.ipynb #f8d4d24d
EXCLUDED_PROCESSES = {'sudo','python'}

# %% ../nbs/00_config.ipynb #13babdaf
DATABASE_FILENAME = "snooper.db"

# %% ../nbs/00_config.ipynb #941e072f
DATA_RETENTION_DAYS = 7

# %% ../nbs/00_config.ipynb #d380659a
FG_APP_MONITORING_INTERVAL_SECONDS = 2

# %% ../nbs/00_config.ipynb #97baa2a4
FG_APP_MONITORING_MIN_IDLE_SECONDS = 60

# %% ../nbs/00_config.ipynb #0a8552af
STREAMING_APP_MIN_IDLE_SECONDS = {'youtube': 600, 'netflix': 600, 'twitch': 600}

# %% ../nbs/00_config.ipynb #199d6147
NUM_TOP_APP_IN_REPORT = 10

# %% ../nbs/00_config.ipynb #c58e4eb3
NUM_TOP_WINDOW_IN_REPORT = 5

# %% ../nbs/00_config.ipynb #84bab75b
SHOW_WINDOW_TITLES = True

# %% ../nbs/00_config.ipynb #e2cf94c1
DEFAULT_PAUSE_MINUTES = 30
