"""Central configuration values for Snooper's monitoring, data retention, reporting, privacy, and pause behaviour.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/config.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto #0
__all__ = ['PROCESS_MONITORING_INTERVAL_SECONDS', 'EXCLUDED_PROCESSES', 'DATABASE_PATH', 'DATA_RETENTION_DAYS',
           'FG_APP_MONITORING_INTERVAL_SECONDS', 'FG_APP_MONITORING_MIN_IDLE_SECONDS', 'STREAMING_APP_MIN_IDLE_SECONDS',
           'NUM_TOP_APP_IN_REPORT', 'NUM_TOP_WINDOW_IN_REPORT', 'SHOW_WINDOW_TITLES', 'DEFAULT_PAUSE_MINUTES']

# %% ../nbs/00_config.ipynb #f99ee53a
PROCESS_MONITORING_INTERVAL_SECONDS = 5

# %% ../nbs/00_config.ipynb #f8d4d24d
EXCLUDED_PROCESSES = {'sudo','python'}

# %% ../nbs/00_config.ipynb #cb6bf807
DATABASE_PATH = "snooper.db"

# %% ../nbs/00_config.ipynb #941e072f
DATA_RETENTION_DAYS = 7

# %% ../nbs/00_config.ipynb #d380659a
FG_APP_MONITORING_INTERVAL_SECONDS = 2

# %% ../nbs/00_config.ipynb #97baa2a4
FG_APP_MONITORING_MIN_IDLE_SECONDS = 60

# %% ../nbs/00_config.ipynb #0a8552af
STREAMING_APP_MIN_IDLE_SECONDS = {'youtube': 600, 'netflix': 600, 'twitch': 600}

# %% ../nbs/00_config.ipynb #199d6147
NUM_TOP_APP_IN_REPORT = 5

# %% ../nbs/00_config.ipynb #c58e4eb3
NUM_TOP_WINDOW_IN_REPORT = 5

# %% ../nbs/00_config.ipynb #84bab75b
SHOW_WINDOW_TITLES = True

# %% ../nbs/00_config.ipynb #e2cf94c1
DEFAULT_PAUSE_MINUTES = 30
