"""All configurations for running this app is stored here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto #0
__all__ = ['PROCESS_MONITORING_INTERVAL_SECONDS', 'EXCLUDED_PROCESSES', 'DATABASE_PATH']

# %% ../nbs/00_config.ipynb #f99ee53a
PROCESS_MONITORING_INTERVAL_SECONDS = 5

# %% ../nbs/00_config.ipynb #f8d4d24d
EXCLUDED_PROCESSES = {'sudo','python'}

# %% ../nbs/00_config.ipynb #cb6bf807
DATABASE_PATH = "snooper.db"
