"""Monitoring data will be stored in a SQLlite DB. This module exposes all necessary APIs for the same."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_db.ipynb.

# %% auto #0
__all__ = ['Event', 'log_event', 'get_processes']

# %% ../nbs/01_db.ipynb #e1ae96a1
from fastlite import *
import config as cf

# %% ../nbs/01_db.ipynb #adb72d83
db = database(cf.DATABASE_PATH)

# %% ../nbs/01_db.ipynb #70209393
class Event:
    """The class container for process monitoring"""
    pid: int # process identifier
    app: str # application name
    event_type: str # start of stop
    timestamp: str # time of event
    id: int = None # auto generated primary key

# %% ../nbs/01_db.ipynb #494aceda
def log_event(
    pid: int, # process identifier
    app: str, # application name
    event_type: str, # start of stop
    timestamp: str, # time of event
    ):
    """Creates the database if it does not exist and inserts a record"""
    events = db.create(Event, transform = True)
    e = events.insert(pid=pid, app=app, event_type=event_type, timestamp=timestamp)
    return e

# %% ../nbs/01_db.ipynb #cfd7de6a
def get_processes():
    """Returns application usage with start time, stop time and duration in seconds"""
    return db.q("""
            SELECT 
                s.pid, 
                s.app, 
                s.timestamp AS start_time, 
                e.timestamp AS stop_time,
                (julianday(e.timestamp) - julianday(s.timestamp)) * 86400 AS duration_seconds
            FROM event s 
            JOIN event e 
                ON s.pid = e.pid 
                AND s.app = e.app
            WHERE s.event_type = 'start' 
                AND e.event_type = 'stop'
            """)
