"""Track the active Windows foreground application and persist completed foreground and idle intervals.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/foreground_tracker.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_foreground_tracker.ipynb.

# %% auto #0
__all__ = ['get_foreground_window_info', 'is_streaming_app', 'start_foreground_app_monitoring']

# %% ../nbs/03_foreground_tracker.ipynb #3fc06c45
import psutil
from datetime import datetime
from time import sleep

# %% ../nbs/03_foreground_tracker.ipynb #4cbec422
import snooper_pkg.config as cf
from .db import *
from .idle_detector import *

# %% ../nbs/03_foreground_tracker.ipynb #4939c6b1
import sys
def _require_windows():
    if sys.platform != "win32":
        raise RuntimeError("Windows idle detection is only available on Windows")


# %% ../nbs/03_foreground_tracker.ipynb #9672487f
def get_foreground_window_info() -> tuple[str, int, int, str]:
    "Return the foreground window title, handle, process ID, and process name."
    _require_windows()
    import win32gui, win32process
    hwnd = win32gui.GetForegroundWindow()
    title = win32gui.GetWindowText(hwnd) or "Unknown"
    tid, pid = win32process.GetWindowThreadProcessId(hwnd)
    if not isinstance(pid, int) or pid <= 0: return title, hwnd, -1, "UNKNOWN"
    try: process_name = psutil.Process(pid).name()
    except (psutil.NoSuchProcess, psutil.AccessDenied, ValueError, psutil.Error): return title, hwnd, -1, "UNKNOWN"
    return title, hwnd, pid, process_name

# %% ../nbs/03_foreground_tracker.ipynb #9f7f5ced
def is_streaming_app(
    title: str,  # Foreground window title to inspect
    streaming_app_min_idle_time: dict[str, int | float],  # Title substrings mapped to idle thresholds in seconds
) -> int | float | None:
    "Return the idle threshold for the first configured title match, or `None`."
    for s in streaming_app_min_idle_time.keys():
        if s.lower() in title.lower():
            return streaming_app_min_idle_time[s]
    return None

# %% ../nbs/03_foreground_tracker.ipynb #f101b187
def start_foreground_app_monitoring(
    session_id: str,  # Monitoring session receiving foreground intervals
    stop_event: object,  # Stop signal providing an `is_set()` method
    time_interval: int | float = cf.FG_APP_MONITORING_INTERVAL_SECONDS,  # Seconds between foreground samples
    min_idle_time_gap: int | float = cf.FG_APP_MONITORING_MIN_IDLE_SECONDS,  # General idle threshold in seconds
    streaming_app_min_idle_time: dict[str, int | float] = cf.STREAMING_APP_MIN_IDLE_SECONDS,  # Title-specific idle thresholds
) -> None:
    "Sample foreground state until stopped and record each completed interval."
    fg_dict = {}
    try:
        while not stop_event.is_set():
            title, hwnd, pid, process_name = get_foreground_window_info()
            if is_streaming_app(title, streaming_app_min_idle_time) is not None: 
                min_idle_time = is_streaming_app(title, streaming_app_min_idle_time)
                is_idle = get_idle_seconds() > min_idle_time
            else: is_idle = get_idle_seconds() > min_idle_time_gap
            if is_idle:
                title, hwnd, pid, process_name = "Idle", -1, -1, "IDLE"
            if fg_dict.get("pid") != pid or fg_dict.get("hwnd") != hwnd or fg_dict.get("window_title") != title:
                if fg_dict:
                    fg_dict["end_time"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                    log_fg_app_events(**fg_dict)
                fg_dict = {
                    "session_id":session_id,
                    "window_title": title,
                    "pid": pid,
                    "hwnd": hwnd,
                    "app": process_name,
                    "start_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "is_idle":is_idle,
                    "end_time": None
                }
            else:
                fg_dict["end_time"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            sleep(time_interval)
    except KeyboardInterrupt:
        print("Stopped by user.")
    finally:
        if fg_dict: 
            fg_dict["end_time"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            log_fg_app_events(**fg_dict)

