"""Windows idle-time measurement based on system tick counts for the most recent user input.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/idle_detector.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_idle_detector.ipynb.

# %% auto #0
__all__ = ['LASTINPUTINFO', 'get_last_input_tick', 'get_idle_seconds']

# %% ../nbs/02_idle_detector.ipynb #c6affeda
import ctypes
from ctypes import wintypes

# %% ../nbs/02_idle_detector.ipynb #56597405
import sys
def _require_windows():
    if sys.platform != "win32":
        raise RuntimeError("Windows idle detection is only available on Windows")

# %% ../nbs/02_idle_detector.ipynb #e6a637cf
class LASTINPUTINFO(ctypes.Structure):
    "ctypes representation of the Windows `LASTINPUTINFO` structure."

    _fields_ = [
        ("cbSize", wintypes.UINT),   # Size of this structure in bytes
        ("dwTime", wintypes.DWORD),  # Tick count when the last input occurred
    ]


# %% ../nbs/02_idle_detector.ipynb #3f90a87c
def get_last_input_tick():
    "Call `GetLastInputInfo` and return its last-input tick count in milliseconds."
    _require_windows()

    info = LASTINPUTINFO()
    info.cbSize = ctypes.sizeof(info)
    
    ok = ctypes.windll.user32.GetLastInputInfo(ctypes.byref(info))
    if not ok:
        raise ctypes.WinError()
    return info.dwTime

# %% ../nbs/02_idle_detector.ipynb #2083d992
def get_idle_seconds():
    "Return the elapsed seconds between system uptime and the last input tick."
    _require_windows()
    current_tick = ctypes.windll.kernel32.GetTickCount64()
    last_input_tick = get_last_input_tick()
    return (current_tick - last_input_tick)/1000
