"""Startup orchestration for the monitoring controller, previous-session report, and system-tray interface.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/main.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_main.ipynb.

# %% auto #0
__all__ = ['main']

# %% ../nbs/09_main.ipynb #dd2ab1a5
import snooper_pkg.config as cf
from .monitoring_controller import MonitorController
from .tray import *

# %% ../nbs/09_main.ipynb #dc360bcd
def main():
    "Start monitoring, show the last session report, and run the tray application."
    controller = MonitorController()
    controller.start_monitoring()
    open_last_session_report(controller)
    run_tray(controller)

# %% ../nbs/09_main.ipynb #16946e18
if __name__ == "__main__":
    main()
