"""Poll running processes and record process start and stop events for a monitoring session.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/process_monitor.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_process_monitor.ipynb.

# %% auto #0
__all__ = ['get_current_processes', 'start_process_monitoring']

# %% ../nbs/04_process_monitor.ipynb #ab11b68c
import logging
logger = logging.getLogger(__name__)


# %% ../nbs/04_process_monitor.ipynb #a5091893
import psutil
from datetime import datetime
import time

# %% ../nbs/04_process_monitor.ipynb #46df5250
import snooper_pkg.config as cf
from .db import *

# %% ../nbs/04_process_monitor.ipynb #bccd8472
def get_current_processes(excluded_process_set):
    """Return running `(pid, process_name)` pairs excluding configured processes."""
    cur_procs = [tuple(proc.info.values()) for proc in psutil.process_iter(['pid', 'name'])]
    return set([(pid, proc) for (pid, proc) in cur_procs if proc not in excluded_process_set])

# %% ../nbs/04_process_monitor.ipynb #cd01b55c
def start_process_monitoring(session_id, stop_event, excluded_processes, time_interval=cf.PROCESS_MONITORING_INTERVAL_SECONDS):
    """Poll processes until stopped and log process start and stop events."""
    t0_procs = get_current_processes(excluded_processes)
    while not stop_event.is_set():
        try:
            time.sleep(time_interval)
            t1_procs = get_current_processes(excluded_processes)
            opened_procs = t1_procs - t0_procs
            closed_procs = t0_procs - t1_procs
            cur_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            t0_procs = t1_procs
            if opened_procs:
                for p in opened_procs: log_process_event(session_id, p[0], p[1], 'start', cur_time)
                logger.debug(f"Opened processes: {cur_time}-{opened_procs}")
            if closed_procs:
                for p in closed_procs: log_process_event(session_id, p[0], p[1], 'stop', cur_time)
                logger.debug(f"Closed processes: {cur_time}-{closed_procs}")
        except KeyboardInterrupt:
            break

