"""Build session-level report data from monitoring-session metadata and foreground-event records.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/reporter.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_reporter.ipynb.

# %% auto #0
__all__ = ['build_session_report_data']

# %% ../nbs/05_reporter.ipynb #ceb36334
import pandas as pd

# %% ../nbs/05_reporter.ipynb #7896853f
import snooper_pkg.config as cf

# %% ../nbs/05_reporter.ipynb #e078bae4
def build_session_report_data(session, events):
    "Return session metadata, summary metrics, and event breakdowns as a report dictionary."
    report_data_dict = {}
    report_data_dict['session'] = _session_data(session)
    events_df = _clean_events(events)
    report_data_dict['summary'] = _summary_data(events_df)
    report_data_dict['events'] = _events_data(events_df)
    return report_data_dict

# %% ../nbs/05_reporter.ipynb #2074a73b
from datetime import datetime

def _session_data(session):
    return {'start_time': session['start_time'],
            'end_time': session['end_time'],
            'duration_seconds': ((datetime.fromisoformat(session['end_time']) - datetime.fromisoformat(session['start_time']))
            .total_seconds())}

# %% ../nbs/05_reporter.ipynb #c0e773eb
def _clean_events(events):    
    df = pd.DataFrame(events).copy()
    if len(df) == 0: return df
    df['start_time'] = pd.to_datetime(df['start_time'])
    df['end_time'] = pd.to_datetime(df['end_time'])
    df['duration_seconds'] = (
        df['end_time'] - df['start_time']
    ).dt.total_seconds().clip(lower=0).astype(int)

    df['app_name'] = df['window_title'].apply(lambda x: x.split(' - ')[-1])
    df['clean_title'] = df['window_title'].apply(lambda x: x.split(' - ')[-2] if ' - 'in x else 'Unknown')
    return df

# %% ../nbs/05_reporter.ipynb #f2f8f750
def _events_data(events_df, top_n_apps = cf.NUM_TOP_APP_IN_REPORT , top_n_titles=cf.NUM_TOP_WINDOW_IN_REPORT):
    if len(events_df) == 0:
        return []

    active_df = events_df[events_df['is_idle'] == False].copy()
    if active_df.empty:
        return []

    total_active_seconds = int(active_df['duration_seconds'].sum())
    app_totals = (
        active_df.groupby('app_name', as_index=False)['duration_seconds']
        .sum()
        .sort_values('duration_seconds', ascending=False)
    )
    if top_n_apps > 0: app_totals = app_totals.head(top_n_apps)

    out = []
    for _, app_row in app_totals.iterrows():
        app = app_row['app_name']
        app_seconds = int(app_row['duration_seconds'])

        title_totals = (
            active_df[active_df['app_name'] == app]
            .groupby('clean_title', as_index=False)['duration_seconds']
            .sum()
            .sort_values('duration_seconds', ascending=False)
        )
        if top_n_titles > 0: title_totals = title_totals.head(top_n_titles)

        top_titles = [
            {
                'title': r['clean_title'],
                'duration_seconds': int(r['duration_seconds'])
            }
            for _, r in title_totals.iterrows()
        ]

        out.append({
            'app': app,
            'duration_seconds': app_seconds,
            'percent_active': round(100 * app_seconds / total_active_seconds, 1),
            'top_titles': top_titles,
        })

    return out


# %% ../nbs/05_reporter.ipynb #4777efe4
def _summary_data(events_df):
    if len(events_df) == 0:
        return {
            'total_duration_seconds': 0,
            'active_duration_seconds': 0,
            'idle_duration_seconds': 0,
            'active_percent': 0.0,
            'idle_percent': 0.0,
            'app_switch_count': 0,
            'distinct_app_count': 0,
            'top_app': None,
            'top_app_duration_seconds': 0,
            'longest_idle_seconds': 0,
        }

    df = events_df.sort_values('start_time').copy()
    total_duration_seconds = int(df['duration_seconds'].sum())

    idle_df = df[df['is_idle'] == True]
    active_df = df[df['is_idle'] == False]

    idle_duration_seconds = int(idle_df['duration_seconds'].sum())
    active_duration_seconds = int(active_df['duration_seconds'].sum())

    active_percent = round(100 * active_duration_seconds / total_duration_seconds, 1) if total_duration_seconds else 0.0
    idle_percent = round(100 * idle_duration_seconds / total_duration_seconds, 1) if total_duration_seconds else 0.0

    distinct_app_count = int(active_df['app_name'].nunique()) if len(active_df) else 0
    app_switch_count = int(active_df['app_name'].ne(active_df['app_name'].shift()).sum() - 1) if len(active_df) else 0

    if len(active_df):
        app_totals = (
            active_df.groupby('app_name', as_index=False)['duration_seconds']
            .sum()
            .sort_values('duration_seconds', ascending=False)
        )
        top_app = app_totals.iloc[0]['app_name']
        top_app_duration_seconds = int(app_totals.iloc[0]['duration_seconds'])
    else:
        top_app = None
        top_app_duration_seconds = 0

    longest_idle_seconds = int(idle_df['duration_seconds'].max()) if len(idle_df) else 0

    return {
        'total_duration_seconds': total_duration_seconds,
        'active_duration_seconds': active_duration_seconds,
        'idle_duration_seconds': idle_duration_seconds,
        'active_percent': active_percent,
        'idle_percent': idle_percent,
        'app_switch_count': app_switch_count,
        'distinct_app_count': distinct_app_count,
        'top_app': top_app,
        'top_app_duration_seconds': top_app_duration_seconds,
        'longest_idle_seconds': longest_idle_seconds,
    }
