"""Display a session-usage report in a Tkinter window.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/report_window.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_report_window.ipynb.

# %% auto #0
__all__ = ['fmt_duration', 'show_apps', 'show_summary', 'show_titles', 'update_titles', 'show_report']

# %% ../nbs/06_report_window.ipynb #72dc423a
import snooper_pkg.config as cf

# %% ../nbs/06_report_window.ipynb #3e6ef519
def fmt_duration(seconds):
    """Format a duration in seconds as whole minutes and seconds."""
    return f"{seconds // 60}m {seconds % 60}s"

# %% ../nbs/06_report_window.ipynb #cb5d0b7c
def show_apps(root, report_data):
    """Create and populate the foreground-application summary table."""
    from tkinter import ttk
    tree = ttk.Treeview(root, columns=("time", "percent"))

    tree.heading("#0", text="App")
    tree.heading("time", text="Time")
    tree.heading("percent", text="% Active")

    for i, event in enumerate(report_data["events"]):
        tree.insert("", "end", iid=str(i),
                     text=event['app'],
                       values=(f"{fmt_duration(event['duration_seconds'])}",
                                f"{event['percent_active']}%"))
    tree.pack(fill="both", expand=True)
    return tree

# %% ../nbs/06_report_window.ipynb #a59db5d6
def show_summary(root, report_data):
    """Add the session summary fields to the report window."""
    session = report_data["session"]
    summary = report_data["summary"]

    frame = ttk.LabelFrame(root, text="Session Summary")
    frame.pack(fill="x", padx=10, pady=10)

    ttk.Label(frame, text=f"Start: {session['start_time']}").grid(row=0, column=0, sticky="w", padx=8, pady=3)
    ttk.Label(frame, text=f"End: {session['end_time']}").grid(row=0, column=1, sticky="w", padx=8, pady=3)
    ttk.Label(frame, text=f"Total: {fmt_duration(session['duration_seconds'])}").grid(row=0, column=2, sticky="w", padx=8, pady=3)

    ttk.Label(frame, text=f"Active: {fmt_duration(summary['active_duration_seconds'])} ({summary['active_percent']}%)").grid(row=1, column=0, sticky="w", padx=8, pady=3)
    ttk.Label(frame, text=f"Idle: {fmt_duration(summary['idle_duration_seconds'])} ({summary['idle_percent']}%)").grid(row=1, column=1, sticky="w", padx=8, pady=3)
    ttk.Label(frame, text=f"Apps: {summary['distinct_app_count']}").grid(row=1, column=2, sticky="w", padx=8, pady=3)

    ttk.Label(frame, text=f"Top app: {summary['top_app']}").grid(row=2, column=0, columnspan=3, sticky="w", padx=8, pady=3)

# %% ../nbs/06_report_window.ipynb #d48c08a9
def show_titles(root):
    """Create the table used to show titles for the selected application."""
    frame = ttk.LabelFrame(root, text="Titles for selected app")
    frame.pack(fill="both", expand=True, padx=10, pady=10)

    tree = ttk.Treeview(frame, columns=("time",))
    tree.heading("#0", text="Title")
    tree.heading("time", text="Time")
    tree.pack(fill="both", expand=True)

    return tree

def update_titles(title_tree, report_data, app_tree):
    """Replace title-table rows with title durations for the selected app."""
    for row in title_tree.get_children():
        title_tree.delete(row)
    selection = app_tree.selection()
    if not selection: return
    selected_iid = selection[0]
    selected_event = report_data["events"][int(selected_iid)]   
    for title_info in selected_event["top_titles"]:
        title_tree.insert(
            "",
            "end",
            text=title_info["title"],
            values=(fmt_duration(title_info["duration_seconds"]),)
        )

# %% ../nbs/06_report_window.ipynb #5abd3eb7
def show_report(report_data, report_title = "Usage Report", is_show_titles = cf.SHOW_WINDOW_TITLES):
    """Open the report window and run its Tkinter event loop."""
    import tkinter as tk
    root = tk.Tk()
    root.protocol("WM_DELETE_WINDOW", root.destroy)
    root.title(report_title)
    show_summary(root, report_data)
    app_tree = show_apps(root, report_data)
    if is_show_titles: 
        title_tree = show_titles(root)
        rows = app_tree.get_children()
        if rows:
            app_tree.selection_set(rows[0])
            update_titles(title_tree, report_data, app_tree)
        app_tree.bind("<<TreeviewSelect>>", lambda e: update_titles(title_tree, report_data, app_tree))
    root.mainloop()
