"""Provides system-tray controls for monitoring, reporting, pause and resume, and application exit.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/tray.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_tray.ipynb.

# %% auto #0
__all__ = ['UiDispatcher', 'open_last_session_report', 'open_current_session_report', 'run_tray']

# %% ../nbs/08_tray.ipynb #686e4398
import logging
logger = logging.getLogger(__name__)


# %% ../nbs/08_tray.ipynb #7c09ff25
import threading
import tkinter as tk
from tkinter import simpledialog
from queue import Empty, Queue


# %% ../nbs/08_tray.ipynb #1744d819
import snooper_pkg.config as cf
from .report_window import *

# %% ../nbs/08_tray.ipynb #42695dc0
class UiDispatcher:
    def __init__(self, root):
        self.root = root
        self.queue = Queue()
        self.root.after(100, self._process)

    def submit(self, callback, *args, **kwargs):
        self.queue.put((callback, args, kwargs))

    def _process(self):
        try:
            while True:
                callback, args, kwargs = self.queue.get_nowait()
                callback(*args, **kwargs)
        except Empty:
            pass
        finally:
            self.root.after(100, self._process)


# %% ../nbs/08_tray.ipynb #7d17db0d
def open_last_session_report(
    controller, # Controller used to generate last-session report data
    root,
    submit_ui
):
    """Show the last-session report when report data is available."""
    report_data = controller.generate_last_report_data()
    if report_data:
        submit_ui(
            show_report,
            root,
            report_data,
            "Last Session Report",
        )

def open_current_session_report(
    controller, # Controller used to generate current-session report data
    root,
    submit_ui
):
    """Show the current-session report when report data is available."""
    report_data = controller.generate_current_session_stats()
    if report_data:
        submit_ui(
            show_report,
            root,
            report_data,
            "Current Session Report",
        )

# %% ../nbs/08_tray.ipynb #fc4c738b
def run_tray(
    controller, # Controller that owns monitoring and pause/resume state
    show_last_on_start=False # Whether to show the last session report on app start up
):
    """Start the tray integration and block in the Tkinter event loop until exit."""
    import pystray
    from PIL import Image

    root = tk.Tk()
    root.protocol("WM_DELETE_WINDOW", root.destroy)
    root.withdraw()  # Hide the main window

    ui = UiDispatcher(root)

    def close_tk():
        root.quit()
        root.destroy()
    def on_exit(icon, item):
        if controller.is_running(): controller.stop_monitoring(stop_reason="manual_stop")
        icon.stop()
        ui.submit(close_tk)
    
    def pause_for(icon, item, minutes):
        controller.pause_for(minutes)
        icon.update_menu()
        open_current_session_report(controller, root, ui.submit)
    
    def pause_custom(icon, item):
        # Prompt user for custom pause duration
        ui.submit(ask_pause_duration, icon)

    def ask_pause_duration(icon):
        minutes = simpledialog.askinteger("Pause Duration", "Enter pause duration in minutes:", minvalue=1)
        if minutes:
            controller.pause_for(minutes)
            icon.update_menu()
            open_current_session_report(controller, root, ui.submit)

    def resume_now(icon, item):
        controller.resume_now()
        icon.update_menu()
   
    menu = pystray.Menu(
            pystray.MenuItem("Show last session report",
                            lambda icon, item: open_last_session_report(
                                controller, root, ui.submit
                                )
                            ),
            pystray.MenuItem("Show current session stats", 
                            lambda icon, item: open_current_session_report(
                                controller, root, ui.submit
                            ),
                            enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem(
                "Pause 15 min", 
                lambda icon, item: pause_for(icon, item, 15),
                enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem(
                "Pause 30 min", 
                lambda icon, item: pause_for(icon, item, 30),
                enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem("Pause for...", pause_custom, 
                         enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem(
                "Resume now",
                lambda icon, item: resume_now(icon, item),
                enabled=lambda item: controller.is_paused()
            ),
            pystray.MenuItem("Exit", on_exit),
        )

    image = Image.new("RGB", (64, 64), "blue")
    icon = pystray.Icon("Snooper", image, "Snooper", menu)
    controller.on_state_change = lambda: icon.update_menu()
    controller.on_notify = lambda msg: icon.notify(msg, "Snooper")
    icon.run_detached()

    # Schedule startup report after the Tk event loop begins.
    if show_last_on_start:
        root.after(
            0,
            lambda: open_last_session_report(
                controller,
                root,
                ui.submit,
            ),
        )

    root.mainloop()
