"""Provides system-tray controls for monitoring, reporting, pause and resume, and application exit.

Docs: https://sayanbanerjee32.github.io/snooper_pkg/tray.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_tray.ipynb.

# %% auto #0
__all__ = ['open_last_session_report', 'open_current_session_report', 'run_tray']

# %% ../nbs/08_tray.ipynb #7c09ff25
import threading

# %% ../nbs/08_tray.ipynb #1744d819
import snooper_pkg.config as cf
from .report_window import *

# %% ../nbs/08_tray.ipynb #eabe9c7d
def open_last_session_report(
    controller, # Controller used to generate last-session report data
):
    """Show the last-session report when report data is available."""
    report_data = controller.generate_last_report_data()
    if report_data:
        threading.Thread(target=show_report, args=(report_data,"Last Session Report", ), daemon=True).start()

def open_current_session_report(
    controller, # Controller used to generate current-session report data
):
    """Show the current-session report when report data is available."""
    report_data = controller.generate_current_session_stats()
    if report_data:
        threading.Thread(target=show_report, args=(report_data,"Current Session Report",), daemon=True).start()

# %% ../nbs/08_tray.ipynb #fc4c738b
def run_tray(
    controller, # Controller that owns monitoring and pause/resume state
):
    """Start the tray integration and block in the Tkinter event loop until exit."""
    import pystray
    from PIL import Image
    import tkinter as tk
    from tkinter import simpledialog

    root = tk.Tk()
    root.protocol("WM_DELETE_WINDOW", root.destroy)
    root.withdraw()  # Hide the main window
    
    def on_exit(icon, item):
        if controller.is_running(): controller.stop_monitoring(stop_reason="manual_stop")
        icon.stop()
        root.after(0, root.quit)
        root.after(0, root.destroy)
    
    def pause_for(icon, item, minutes):
        controller.pause_for(minutes)
        icon.update_menu()
        open_current_session_report(controller)
    
    def pause_custom(icon, item):
        root.after(0, ask_pause_duration, icon)
        # Prompt user for custom pause duration
    def ask_pause_duration(icon):
        minutes = simpledialog.askinteger("Pause Duration", "Enter pause duration in minutes:", minvalue=1)
        if minutes:
            controller.pause_for(minutes)
            icon.update_menu()
            open_current_session_report(controller)

    def resume_now(icon, item):
        controller.resume_now()
        icon.update_menu()
   
    menu = pystray.Menu(
            pystray.MenuItem("Show last session report", lambda icon, item: open_last_session_report(controller)),
            pystray.MenuItem("Show current session stats", 
                            lambda icon, item: open_current_session_report(controller),
                            enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem(
                "Pause 15 min", 
                lambda icon, item: pause_for(icon, item, 15),
                enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem(
                "Pause 30 min", 
                lambda icon, item: pause_for(icon, item, 30),
                enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem("Pause for...", pause_custom, 
                         enabled=lambda item: controller.is_running()
            ),
            pystray.MenuItem(
                "Resume now",
                lambda icon, item: resume_now(icon, item),
                enabled=lambda item: controller.is_paused()
            ),
            pystray.MenuItem("Exit", on_exit),
        )

    image = Image.new("RGB", (64, 64), "blue")
    icon = pystray.Icon("Snooper", image, "Snooper", menu)
    controller.on_state_change = lambda: icon.update_menu()
    controller.on_notify = lambda msg: icon.notify(msg, "Snooper")
    threading.Thread(target=icon.run, daemon=True).start()
    root.mainloop()
